### ISSUE TITLE
Tick are still computed even if all three minor-tick, tick-label, and tick-mark are set to not visible

### ISSUE THREAD

**Issue by SylvainBertrand** [GSI-CS-CO/chart-fx#105]
Hi!

So I'm using the `XYChart` and stripped it to the bare minimum, i.e. the plotted data and the legend. I discovered that when creating a bunch of new charts, i.e. up to 24 at once, the creation time was pretty significant in my case. Profiling the creation of the charts revealed that the computation of the tick info is the culprit, more precisely `AbstractAxis.recomputeTickMarks(AxisRange)`:
![image](https://user-images.githubusercontent.com/15932806/75169584-6aaab900-56ee-11ea-825c-9465c9f066b5.png)

The current workaround I've found is to basically make a new implementation of `AbstractAxis` which is the same as `NumericAxis` but without the calculation of the tick marks. This works but ends up in a bunch of code duplication and isn't ideal.

Ideally either of the two following options would work great for me:
- `NumericAxis` is smart about the computation of the tick marks regarding the state of the properties: `minorTickVisible`, `tickLabelsVisible`, and `tickMarkVisible`.
- `NumericAxis` isn't final and allows to make such modification via overriding.

I realize this is probably a singular setup and that the first option would require some work with little benefit for you. maybe I could help if that'd be the desired option.

Thank you!

**Comment by RalphSteinhagen** [comment]
Hi,
this is indeed one of the rare corner use-cases. The conditional skipping of re-computing the ticks/labels depending on the `minorTickVisible`, `tickLabelsVisible`, and `tickMarkVisible` seems to be the most promising/least effort option. Do you need the `GridRenderer` that's the only other dependency that I reckon needs the ticks. 

Alternatively, since you do not seem to need ticks/labels, have you considered implementing either the `Axis` interface or to derive only from `AxisRange` or `DataRange` directly?
AbstractAxis is not a mandatory class and deals primarily with formatting, CSS style-sheeting and computation of ticks etc. which you may not need. 

The graph will also plot fine as long as you implement only the data-to-pixel and pixel-to-data transforms. 

Food for thought.

**Comment by SylvainBertrand** [comment]
Indeed I'm not using the `GridRenderer` making this even more of a weird use-case.
Thanks for the advice, seems like a better option than what I thought, I'll give it a shot!

Thank you!!
