### ISSUE TITLE
11.1.3 tick label gap rendering change

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#122]
I just tried to update to the latest version and found that the x-axis labels are now being rendered outside the lower bounds. It seems that the behavior of the tick label gap has changed from being applied horizontally to being applied all around.

Was this a conscious choice? If so, is there a way to get the old behavior back?

**11.1.2** (tick label gap 30)
![image](https://user-images.githubusercontent.com/5491587/76524794-fbadbe00-646a-11ea-9896-364ecbd17892.png)

**11.1.3** (tick label gap 30)
![image](https://user-images.githubusercontent.com/5491587/76524724-d5881e00-646a-11ea-8aa2-bff86fece28f.png)

**11.1.3** (tick label gap 0)
![image](https://user-images.githubusercontent.com/5491587/76525275-d53c5280-646b-11ea-9729-ab0a190ef13d.png)

**Comment by wirew0rm** [comment]
It was a conscious bugfix, but we did realize that this option could also be used for your purpose.

As the [javadoc](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-chart/src/main/java/de/gsi/chart/axes/Axis.java#L120-L123) says, the purpose of this property is to set the spacing between tick mark and label. That it also affects spacing between the labels is only because for the relatively small values where this setting is useful, it looks nicer if you also add a little bit more spacing there.

We are thinking about adding a separate property (e.g labelSpacing) for spacing between labels which should be pretty straightforward. In the meantime, the number of ticks could also be adjusted by either setting maxMajorTickLabelCount (defaults to 20) or adjusting tickUnit, but of course this does not work as nicely for changing data ranges and window sizes.

As always, thanks for the detailed report  :+1:

**Comment by ennerf** [comment]
The `maxMajorTickLabelCount` seems like a better way to go about it. Thanks 👍
