### ISSUE TITLE
Missing lines when data point is outside of x axis range

### ISSUE THREAD

**Issue by zanzica** [GSI-CS-CO/chart-fx#130]
When I have two values A and B as subsequent values in a data set, and the x value of one of them (e.g. of A) is just outside the x axis range, the line to the other data point (e.g. B) is sometimes (but not always) not drawn. This is especially noticeable when the x axis range is shifted: Lines at the range edges suddenly vanish or appear. 
This does not always happen when one data point is outside of the visible range: There seems to be a threshold distance to the x axis range until/from which on the lines are drawn.

I would expect the lines from an invisible point to a visible point to be drawn always (as long as both data points are contained in the data set). [Alternativelly: Never drawing them would be consistent, but IMO not desirable.]

Please see attached example program. 
[DEMO_MissingValue.txt](https://github.com/GSI-CS-CO/chart-fx/files/4356405/DEMO_MissingValue.txt)
The buttons on the bottom can be used to shift the x axis range. By shifting multiple times, we can see that points move out of the visible range with their lines still drawn, then the lines suddenly vanish. On the other side, there appears to be a gap in the graph until a line to a not yet visible data point suddenly appears.
4 Shifts to the right, line on the left still visible, line one the right not yet visible:
![2020-03-19_DemoMissingValues_4Shifts](https://user-images.githubusercontent.com/14939118/77103661-0d6b0480-6a1b-11ea-9ac4-9b00230e88f6.png)
5 Shifts to the right, line on the left vanished, line one the right appeared:
![2020-03-19_DemoMissingValues_5Shifts](https://user-images.githubusercontent.com/14939118/77103519-d1d03a80-6a1a-11ea-9af7-adc3132a1fc0.png)
By shifting back and forth, it becomes obvious that the data points are still contained by their data set, they/their lines are simply not drawn.

I could reproduce this behaviour with LimitedIndexedTreeDataSet, FifoDoubleErrorDataSet, and CircularDoubleErrorDataSet. I did not check any other datasets.

As suggested by @wirew0rm via chat, I turned off data reduction via 
`renderer.setPointReduction(false)`. This did not change the outcome.

**Comment by RalphSteinhagen** [comment]
Hi Anne (@zanzica) and welcome to GitHub!

This is by design and for performance reasons to minimise the necessity for doing (costly) interpolation between points and/or clipping at the boundaries (Canvas clipping is costly for large DataSets with JavaFX, you may check this e.g. via turning the `isAssumeSortedData()` off)

The ErrorDataSetRenderer always draws from the first to the last point that are within the visible axis range. The corresponding code can be found at: https://github.com/GSI-CS-CO/chart-fx/blob/22e5f2ab74b4f2f3024283bd4006e3c6edbbf047/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/ErrorDataSetRenderer.java#L691-L699

For most DataSets (ie. those derived from AbstractAxis) this is implemented via a fast binary search algorithm, see e.g.
https://github.com/GSI-CS-CO/chart-fx/blob/22e5f2ab74b4f2f3024283bd4006e3c6edbbf047/chartfx-dataset/src/main/java/de/gsi/dataset/spi/AbstractDataSet.java#L488

You have the following options: you may either
a) set the `isAssumeSortedData()` to 'off', or
b) override the `public int getIndex(final int dimIndex, final double x)` in your DataSet to include always the point before and after the view range (if they exist).

Hope this helps and Happy Coding!

**Comment by zanzica** [comment]
I suspected that it might be connected to performance improvements. If including one outside point on each side of the drawing range, as implemented in your pull request #132 , does not cause any (relevant) performance degradation, I would be happy to see it merged. Otherwise I'll try to implement something similar in [DataSet]#getIndex as you suggested.

Thanks for the prompt reaction!
