### ISSUE TITLE
Can't run samples from command line windows

### ISSUE THREAD

**Issue by hannabasha** [GSI-CS-CO/chart-fx#161]
Hi,

So, I downloaded the charts and tried to run them by doing
`mvn compile install`
but that unfortunately failed with the following error

 ```
2 errors
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for chartfx 11.1.0-SNAPSHOT:
[INFO]
[INFO] chartfx ............................................ SUCCESS [  2.575 s]
[INFO] dataset ............................................ SUCCESS [ 23.456 s]
[INFO] math ............................................... SUCCESS [ 23.436 s]
[INFO] chartfx-chart ...................................... FAILURE [ 41.912 s]
[INFO] acc ................................................ SKIPPED
[INFO] chartfx-samples .................................... SKIPPED
[INFO] report ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:31 min
[INFO] Finished at: 2020-04-20T17:08:11+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project chartfx-chart: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - D:\chart-fx\chartfx-chart\src\main\java\de\gsi\chart\ui\HiddenSidesPane.java:34: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Screenshot</h3> The following screenshots shows the right side node hovering over a table after it was made
[ERROR]    ^
[ERROR] D:\chart-fx\chartfx-chart\src\main\java\de\gsi\chart\plugins\ParameterMeasurements.java:24: warning: empty <p> tag
[ERROR]  * <p>
[ERROR]    ^
[ERROR] D:\chart-fx\chartfx-chart\src\main\java\de\gsi\chart\ui\SidesPane.java:25: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Screenshot</h3> The following screenshots shows the right side node hovering over a table after it was made
[ERROR]    ^
[ERROR]
[ERROR] Command line was: "C:\Program Files\Java\jdk-13.0.2\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'D:\chart-fx\chartfx-chart\target\apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :chartfx-chart

D:\chart-fx>
```

I am using java 13.0.2 with maven 3.6.3.

I also tried that with versions 14.0.1 and 11.0.6 with no luck.

Am I missing anything? I am new to maven. So any help would be appreciated!

Thank you!

**Comment by RalphSteinhagen** [comment]
@hannabasha my initial gut feeling is that you are using a not (yet fully) supported/tested combination of JDK and OpenJFX. 
The specific error (if one may call this actually an "error") seems to a be related to a recently tightened interpretation of the JavaDoc syntax rules in the latest [non-LTS JDK](https://www.oracle.com/technetwork/java/13-relnote-issues-5460548.html) version w.r.t. the previous JDK8/11 compatible ones.  I will try to fix these ones in the upcoming release.

Meanwhile: have you tried the [example usage](https://github.com/GSI-CS-CO/chart-fx#example-usage) or [snapshot release](https://github.com/GSI-CS-CO/chart-fx#using-the-snapshot-repository) versions in particular? These work out-of-the-box without compiling the project from scratch. Also, if you use Eclipse or another similar IDE, you should be able to run the samples without building the whole project (since you can safely ignore/skip the JavaDoc generation, which is only really needed while making and pushing new releases to Maven central).

Alternatively, you may also try to run `mvn` with skipping the Javadoc generation part through using the `-Dmaven.javadoc.skip=true` argument, or locally (less preferred) suppress the setting 
`<failOnError>false</failOnError>` entirely in the corresponding pom.xml Javadoc configuration as described [here](https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete).

N.B. regarding versions: Please note -- since we use Chart-fx internally in a production environment -- that Chart-fx needs to follow a perhaps more conservative LTS JDK version convention of
* LTS JDKs <= 11.0.6
* Java lang. features <=1.8 (<-> legacy Oracle/OpenJDK8 support), and
* OpenJFX/JavaFX version <= 13.0.1.
Combinations outside these boundaries have not been fully tested, are partially a bit experimental, and are also not guaranteed to always work with all libraries by the Oracle/IBM/OpenJFX folks upstream, see e.g.: ["OpenJFX N is formally compatible with JDK N and N-1"](https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX#BuildingOpenJFX-OpenJDK). In the case of OpenJFX 13.0.1 we seem to be lucky w.r.t. JDK 11.0.6.

**Comment by hannabasha** [comment]
@RalphSteinhagen thanks for your response!

So, I tried the example [FourierSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/akrimm-auto-module-name/chartfx-samples/src/main/java/de/gsi/math/samples/FourierSample.java) example. I used Intellij with Java jdk 11.0.6, language level 8 with Javafx 13. my gradle.build looks like this

```
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
}
javafx {
    version = "13"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
group 'org.example'
version '1.0-SNAPSHOT'
sourceCompatibility = 1.8
repositories {
    mavenCentral()
}
dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    implementation 'de.gsi.chart:chartfx-chart:11.1.4'
    implementation 'com.aparapi:aparapi:2.0.0'
}
mainClassName = 'Main'
```

Unfortunately, I get the following error

```
10:36:56 AM: Executing task 'run'...

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :configJavafxRun

> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
4 actionable tasks: 2 executed, 2 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.6\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 325ms
10:36:57 AM: Task execution finished 'run'.
```

I am not sure running with stacktrace is any helpful, I can provide them if you want, I just didn't provide them now so this comment won't be too long to look at.

On the other hand, I noticed if I provide the jdk folder provided with the intellij "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1\jbr", the example would run fine except for a list of exceptions in the terminal that says

`Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: ControlsFX Error: ControlsFX 11.0.0 requires at least Java Version 9`

After inspecting, I noticed that the jdk folder provided by intellij contains Javafx jar files and the javafx 13 I provided in gradle is no longer used and the javafx version in my system becomes 10.

And to double check a little further, this issue only happens when including chartfx as a dependency and not other dependencies.

I am sorry for this long comment and I appreciate your help.
Thank you!

**Comment by wirew0rm** [comment]
I read up about the `compile group` vs `implementation` difference (see [here](https://stackoverflow.com/a/44493379)) and it seems you can also use `api` which will also add the chart-fx dependencies transitively to your gradle project.

Could you try to use `api` instead, maybe that will make javafx available for your project?

About javafx being inside the jdk folder or not, this used to be the default on java 1.8, where javaFX was contained in the jdk. Nowadays javafx is a separate dependency and can be obtained by the different build systems, but because many old applications still assume javafx to be on the classpath some linux distributions and some IDEs startet repackaging javaFX into the jdk. But this prevents you from using different javaFX versions for different projects and leads to build system errors at least with maven+eclipse (`module javafx.<module> is provided be multiple modules: UNNAMED, javax.<module>`).
If you use openjfx as a maven/gradle dependency it will be downloaded to your local repository with the version specified by you and the build system will take care of adding its path to the class-/modulepath.

PS: you do not need to limit yourself to language level 1.8, that is just what is used internally for chart-fx development.

**Comment by hannabasha** [comment]
Thanks for explaining the older/newer versions of java and javafx. It makes a lot more sense now. And I also upgraded the language level to 11.

So, I had to change my plugin from `java` to `java-library` to be able to use `api`. However, that didn't fix the problem. I cleaned and re-built gradle with no use.

Any other ideas why I am encountering that issue?

**Comment by hannabasha** [comment]
Hi,
so I tried with java jdk 11.0.6 and 14.0.1 with `api` and `implementation` and Javafx version 14, it passed the exception of not finding the module and now it's throwing an exception inside adding the chartfx plugins as in the following code
`getPlugins().add(new ParameterMeasurements());`
the exception I am receiving right now is the following

```
Caused by: java.util.ServiceConfigurationError: org.controlsfx.glyphfont.GlyphFont: Provider org.controlsfx.glyphfont.FontAwesome could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.controlsfx.glyphfont.GlyphFontRegistry.<clinit>(GlyphFontRegistry.java:67)
	at org.controlsfx.glyphfont.Glyph.setFontFamily(Glyph.java:250)
	at org.controlsfx.glyphfont.Glyph.<init>(Glyph.java:122)
	at de.gsi.chart.plugins.ParameterMeasurements.getMenuBar(ParameterMeasurements.java:72)
	at de.gsi.chart.plugins.ParameterMeasurements.lambda$new$0(ParameterMeasurements.java:57)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at de.gsi.chart.plugins.ChartPlugin.setChart(ChartPlugin.java:208)
	at de.gsi.chart.Chart.pluginAdded(Chart.java:937)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.gsi.chart.Chart.pluginsChanged(Chart.java:954)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at utility.DemoChart.<init>(DemoChart.java:57)
```
and if I scroll down I see the following exception too

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to unnamed module @392d09b6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at impl.org.controlsfx.ReflectionUtils.addUserAgentStylesheet(ReflectionUtils.java:225)
	at org.controlsfx.glyphfont.GlyphFont.<clinit>(GlyphFont.java:57)
```

However, if I would comment out adding the plugins, it works fine but without the plugins.

Any ideas to help would be appreciated!

**Comment by wirew0rm** [comment]
Possibly relevant controlsfx issue: controlsfx/controlsfx#1245
This also links to their wiki page about fixing access violation problems.

Note that chartfx is developed on javafx13, so while things might work with javafx14, you might encounter more problems there than on the versions @RalphSteinhagen mentioned.

**Comment by hannabasha** [comment]
@wirew0rm thanks for linking that issue and the wiki, it's helpful to know that. However, I did try that and it didn't work. I think it's because I am not linking GlyphFont in my Project, to me it seems that it's coming from chartfx.

I understand the javafx13 version, the thing is as mentioned in my second comment, I am faced with the following exception
`java.lang.module.FindException: Module javafx.controls not found`

**Comment by RalphSteinhagen** [comment]
>  to me it seems that it's coming from chartfx.
@hannabasha Chart-fx works also with gradle and w/o modifications to the library itself. Your issue seems to be build system related. 

Java introduced with JDK9 a [Jigsaw](https://openjdk.java.net/projects/jigsaw/) module system that (among other things) requires that modularised packages need to be explicitly exported to unnamed modules (which Chart-fx, for the time being, is due to reasons outlined in #160). [Workarounds](https://blog.codefx.org/java/five-command-line-options-hack-java-module-system/) for this have been documented elsewhere. Maven (through the exec plugin) and/or e.g. the Eclipse IDE (via putting all dependencies into the classpath) provide implicit solutions for that.

Following is a MVP `build.gradle` file for a SimpleChartSample-style example w/o having to define a `module-info.java`:
```
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
}

sourceCompatibility = 11
targetCompatibility = 11

version = '0.0.1'
group = 'ch.steinhagen.chart.sample'
mainClassName = 'ch.steinhagen.chart.sample.LaunchTestApplication'

javafx {
    version = "13.0.1"
    modules = [ 'javafx.controls', 'javafx.fxml']
}

run {
    // add additional exports where necessary (ie. used)
    jvmArgs = [ '--add-exports=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED', 
                '--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED', 
                '--add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED',
                '--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED']
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'de.gsi.chart:chartfx-chart:11.1.4'
}
```

Please note that you may need to add additional exports depending on which further sub-functionalities/packages you are using from other modules. Hope this helps.

**Comment by hannabasha** [comment]
@RalphSteinhagen  thank you so much!

Those jvmArgs did the trick for me! I appreciate all your help and time guys!
