### ISSUE TITLE
JDK13 change that is possibly useful for rendering performance

### ISSUE THREAD

**Issue by MichelMunoz** [GSI-CS-CO/chart-fx#162]
Since performance was and is the core goal of your project, and you seemed unsatisfied with the final performance obtained.
So, just in case it has not already been taken into account in your project, at first glance, the following change in openJdk might be of interest to you "Add native rendering support by supporting WritableImages backed by NIO ByteBuffers" :
[https://bugs.openjdk.java.net/browse/JDK-8226947](https://bugs.openjdk.java.net/browse/JDK-8226947)
[https://bugs.openjdk.java.net/browse/JDK-8167148](https://bugs.openjdk.java.net/browse/JDK-8167148)

See also those discussions
[https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-June/023347.html](https://mail.openjdk.java.net/pipermail/openjfx-dev/2019-June/023347.html)
and a project testing it
[https://github.com/caprica/vlcj/issues/883](https://github.com/caprica/vlcj/issues/883)
another that integrated it
[https://github.com/miho/NativeFX](https://github.com/miho/NativeFX) : 

> We started with a direct buffer and used the PixelWriter interface to update a WritableImage that displays the content. With JavaFX 13 we added support for the new PixelBuffer API. Early tests show that we can expect a performance boost of around 50%. 

And two demo projects:
[PixelBuffer Tests](https://github.com/jgneff/pixel-buffer)
[JFXToolsAndDemos / NativeRenderingCanvas](https://github.com/mipastgt/JFXToolsAndDemos/blob/master/jfxtools-canvas/docs/NativeRenderingCanvas.adoc) : goes into details on emulating double buffering and having an external renderer

It seems to be posterior (java 13) to your benchmarks, so this might be a possible venue to explore, it could help to achieve your main goal.
I apologize in advance if its of no use to your project.

**Comment by wirew0rm** [comment]
Hey there, thanks for your interest in chart-fx.

The `WritableImage` ByteBuffer API was already brought up in #32, but the discussion about this happened outside of the Issue, so I'm gonna sum up our take on this topic here.
I actually played around with it for a later discarded `ContourDataSetRenderer` rewrite (it was later rewritten using the regular PixelWriter API) and the takeaway is, that there really isn't a big performance win for our use case. Basically this API allows native code to write Pixels to the graphics stack without having to copy the data to java memory and back to native memory, but since our renderers are written in java, we do not get this benefit. We could of course reimplement our renderers in native code and integrate them with `writableImage` but that would mean compiling and shipping native code and basically reimplementing the javafx renderer parts we use.

I'm gonna close this for now, please feel free to reopen or comment if you think that we overlooked something in our evaluation of the API.

Also note that you can also write your own Renderers and in them you are of course free to use native code if you want to play with this.

**Comment by MichelMunoz** [comment]
It makes sense to close the ticket then. Thanks for answering.
