### ISSUE TITLE
StackOverflowError in method binarySearch()

### ISSUE THREAD

**Issue by Vado101** [GSI-CS-CO/chart-fx#181]
Hello, everybody! I try to make oscilloscope using chart-fx. I use FloatDataSet to display oscilloscope data. I get data blocks from sound cart and send send it to display a chart. When I run my program I often get an error: 

```
Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133)
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133)
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133)
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133)
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133)
	at de.gsi.dataset.spi.AbstractDataSet.binarySearch(AbstractDataSet.java:133) etc.
```

How can I fix it? Help me please.

**Comment by RalphSteinhagen** [comment]
Hi @Vado101, which specific DataSet implementation do you use or do you use your own? 

In case you use one of Chart-fx's default implementation: is your input data sorted? The binarySearch recursion typically fails in case of the latter if a non-sorting DataSet is chosen. The `LimitedIndexedTreeDataSet` is usually a safe choice for arbitrary data. Due to the large CPU/memory performance penalty, sorting is not implemented by default for all DataSets and/or renderer.

In case you use your own DataSet implementation: you need to implement/override the 
`int getIndex(int dimIndex, double x)` that handles your type of (potentially unsorted) input data. 

Without a specific MVP example, there's unfortunately not much more to speculate upon.

I hope the above hints are helpful nevertheless. :-)

**Comment by Vado101** [comment]
Thanks so much for the help! I solved my problem. I used multiple threads to draw a oscilloscope. Threads were't synchronized, so this error occurred. :)

**Comment by Vado101** [comment]
The indicated error occurred again. I use `FloatDataSet dataSet`. I have a method in which I fill in my data:

`public void setAxesValues(float[] signalData) {
        xValues = new float[signalData.length];
        yValues = new float[signalData.length];

        float sampleRate = 44100.0f;

        for (int i = 0; i < signalData.length; ++i) {
            xValues[i] = ((float) i) / sampleRate;
            yValues[i] = signalData[i];
        }

        dataSet.set(xValues, yValues);
}`

Please tell me what I should sort?

**Comment by wirew0rm** [comment]
Can you try to get a full stack trace to find out, where the call to binarySearch is coming from? E.g. set a breakpoint on StackOverflowException in Eclipse and debug.

From the code you've shown everything should be fine, x is sorted and dataSet.set is writeLock guarded, so the xValues of dataSet should at all times be sorted.

Also more context on your setup would help (which Renderer(s), any Plugins added, any other datasets). or even better a minimal viable program ;)

How big is `signalData.length`? The recursion depth for binarySearch should be log_2(signalData.length) independent of whether the data is sorted, I suspect that somewhere binarySearch is called inside a loop.

**Comment by Vado101** [comment]
Sorry for the long answer. I made a minimally viable program, which is located at the link [https://github.com/Vado101/chart-fx/tree/master/chartfx-samples/src/main/java/de/gsi/my/test/oscilloscope](url)

I conducted many tests and noticed that this error occurs when the RAM or processor is heavily loaded.

**Comment by RalphSteinhagen** [comment]
@Vado101 we needed to modify your MVP example to compile and were unfortunately not able to reproduce your observations with the information provided. 

It was actually hard to 'heavily load' the CPU/GC with the provided example and additional other samples were necessary to run in the background.
![image](https://user-images.githubusercontent.com/46007894/84987896-52e5bd80-b141-11ea-832b-3085a78f8e97.png)

Our assumption is that the issue is more likely in your user code (ie. where your MVP originates from) and that the stack memory space exhaustion may originate there and/or the thread that receives the samples from the audio driver. You may increase the stack space via the corresponding VM argument and see if this changes something in your code.

Aside that, some notes on your MVP example:
* Java sources should have a `.java` file extension
* the `private final String DEFAULT_MIXER_DESCRIPTION = "DirectSound Capture";` is hard-coded which prevents the example to run on Linux (I presume you are a Windows developer, we bypassed this to the default/first source)
* there are a few unnecessary performance penalties in the example due to
  * frequent re-allocation of [`float[]`and `byte[]`](https://github.com/Vado101/chart-fx/blob/39ff4a887d35b5f01731fd98e85c524fe94bad96/chartfx-samples/src/main/java/de/gsi/my/test/oscilloscope/core/ReaderModule#L53-L54) buffers -> you may want to use chart-fx's [DoubleArrayCache](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-dataset/src/main/java/de/gsi/dataset/utils/DoubleArrayCache.java) helper functions and to have one static byte array
  * use of `float[]`: `float` saves space but has a performance penalty due to the unavoidable internal copying/conversions to `double`. We tested this also for chart-fx as a whole, and -- besides saving heap memory space for very large DataSets (>10M points) -- the other JVM/JavaFX side-effects negate any CPU caching performance gain (N.B. this is different for C/C++ where such optimizations are common).
  * the return value of `int count = reader.getData(dataByte, dataByte.length);` in [here](https://github.com/Vado101/chart-fx/blob/39ff4a887d35b5f01731fd98e85c524fe94bad96/chartfx-samples/src/main/java/de/gsi/my/test/oscilloscope/core/ReaderModule#L57) is ignored. While the read function likely return the requested number of samples, it does not have to and may return with less (see [JavaDoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/sound/sampled/TargetDataLine.html#read(byte%5B%5D,int,int)))
  * since you already allocate two new float arrays per audio-frame you may also change [following line](https://github.com/Vado101/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/my/test/oscilloscope/OscilloscopeMain#L106) from
    ```java
    dataSet.set(xValues, yValues);
    ```  
    to
    ```java
    dataSet.set(xValues, yValues, count, false);
    ```
    which addresses the previous comment and re-uses (in-place) the existing float array.

N.B. If you are looking for high-performance plotting, you may want to wrap your existing data structures with a `DataSet` interface implementation rather than doing a copy-paste to one of the default `[Float/Double]DataSet` implementations. These are OK for general use but are not as optimized as wrapping your own data objects.

**Comment by Vado101** [comment]
@RalphSteinhagen thank you so mach for your help! I followed your advice and it solved my problem. I didn’t answer for a long time because I wanted to make sure that the problem really went away.

This helped the most:

> since you already allocate two new float arrays per audio-frame you may also change following line from
`dataSet.set(xValues, yValues);`
to
`dataSet.set(xValues, yValues, count, false);`

**Comment by RalphSteinhagen** [comment]
@Vado101 am glad that this helped to resolve your problem.

Is this a private or public application of yours that used Chart-Fx? We are collecting examples and plan to set up a more documentation-oriented/tutorial-type site on how to use this little lib, common practices, and also showcases what can be done with it. We'd be happy to include your example app if you agree.

Looking forward!

**Comment by Vado101** [comment]
@RalphSteinhagen it is a proprietary project that uses this library to display the spectrogram and oscilloscope of the received signals. When I have time, I will only get from my project the part that uses the library. It will look like a signal analyzer. I will gladly give you this part of the project) But it won't happen soon)

**Comment by RalphSteinhagen** [comment]
@Vado101 you do not need to share the code if this is inconvenient for you. A simple screenshot or simple demo video would also be fine. :+1:
