### ISSUE TITLE
setTimeAxis doesn't seem to work

### ISSUE THREAD

**Issue by sirolf2009** [GSI-CS-CO/chart-fx#22]
I'm building a chart for btc analysis, but I can't seem to set my x axis to a time axis. Here's my code
```xtend
val xAxis1 = new DefaultNumericAxis()
xAxis1.setTimeAxis(true)
val yAxis1 = new DefaultNumericAxis("y axis", "$")
yAxis1.setAnimated(false)
```
And this is what my chart looks like, my x axis still displays numbers instead of dates
![image](https://user-images.githubusercontent.com/3534736/62779865-9cdb2d00-bab4-11e9-86e0-742621d5b0cf.png)
What am I doing wrong? I'm using v 8.0.2

**Comment by RalphSteinhagen** [comment]
How do you add the axis to the chart? Would need a bit more lines... ;-)

Have a look at one of the time axis samples, e.g. [TimeAxisSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/TimeAxisSample.java)
or [TimeAxisRangeSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/TimeAxisRangeSample.java), or [RollingBufferSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/RollingBufferSample.java), [...](https://github.com/GSI-CS-CO/chart-fx/tree/master/chartfx-samples/src/main/java/de/gsi/chart/samples).

Please note that the time axis feature assumes EPOCH time in units of seconds (ie. since 01/01/1970). Also, keep in mind your local time-zone setting.

Have fun!

**Comment by sirolf2009** [comment]
Aah, I see. I was using epoch time in millis, not seconds. Now it works, thanks
