### ISSUE TITLE
[Question] Styling guide for dark theme

### ISSUE THREAD

**Issue by deepthought-64** [GSI-CS-CO/chart-fx#228]
Sorry, i don't know where to turn with my question so I'll post it here. 

Firstly, i really enjoy working with chart-fx. It is by far the best charting lib for my use case that I have ever come across! Thanks for your effort!

I am currently writing an application which has a dark theme and I was not yet able to completely figure out how to style chart-fx so that it renders nicely on a dark background. I am currently trying to find how to set the color of label of the axis (i suppose it is the axis tick label?) but what ever I do, it remains black (see attached screenshot).

I have tried setting it via css 
```
.axis-label {
     /*this sets the axis label ("value [m/s²]") correctly*/
    -fx-fill: lightgrey;

    /*these two don't seem to work*/
    -fx-text-fill: yellow;
    -fx-tick-label-fill: red
}
```
or via the Axis using `setTickLabelFill = Color.CYAN;`

The result is always a chart with black tick labels:
![image](https://user-images.githubusercontent.com/5528887/87551141-2ffee880-c6b0-11ea-88c3-c0aa4dc17915.png)

I also checked the [JavaFX Documentation for Styling Charts with CSS](https://docs.oracle.com/javafx/2/charts/css-styles.htm) as well as the [JavaFX CSS Reference Guide](https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#linechart) but found nothing that helped me.

I would appreciate it very much if you can help me with this styling issue or direct me to a place where i can find more help! Thanks!

**Comment by RalphSteinhagen** [comment]
@deepthought-64 thanks for the kind words. We have been looking into the dark theme ourselves to and in preparation reworked the way how chart-fx handles CSS. For details see PR #215.

The styling is similar but the field names are not always exactly the same as for the stock Oracle  Chart implementation. For initial guidance, you may have a look at the new [AbstractAxisParameter.java](https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.2.0/chartfx-chart/src/main/java/de/gsi/chart/axes/spi/AbstractAxisParameter.java#L142-L152) notably the properties defined via the new CSS mechanism that looks like `CSS.createObjectProperty(this, "tickLabelFill", ..)` the second argument relates directly to the CSS property name ie. in this case `-fx-tickLabelFill` the rest behaves as before.

We will need to update (actually write) a bit more documentation on that. @deepthought-64 would you be willing to help?

The above PR isn't merged yet to master since there are some other (unrelated) changes that we'd like to incubate (see #45 for details). However, we plan to make a release sometime this summer. Hopefully rather sooner than later.

Let me hope if the above hints help.

**Comment by wirew0rm** [comment]
I would like to add, that the tick-mark-fill is a property of the axis, not the axis label, except from that everything was right. This is the correct css snippet for the current release version:

``` css
.axis {
    -fx-tick-label-fill: blue;
}
```

**Comment by deepthought-64** [comment]
@RalphSteinhagen thanks very much for the quick reply. definitly looking forward your implementation of a dark theme. :)

Unfortunately I was still not able to set the `tickLabelFill`.
I tried setting it via css (exactly like @wirew0rm said) in a .css file that i attached to the chart node via (`chart.getStylesheets().add(...)`. 

I also tried setting it on the axis either via the property `tickLabelFill` or via style:
```kotlin
val axis = DefaultNumericAxis("value", unit.description)
axis.tickLabelFill = Color.CYAN
axis.style = "-fx-tick-label-fill:white"
this.chart.axes.add(axis)
```

I am sure it is just something stupid that I have overlooked, but I cant find it. :-/

And sure I'll be willing to help contribute to a documentation!

**Comment by deepthought-64** [comment]
Could it be that the tickLabelFill is just not used? I was looking through the `GridRenderer` and only saw the `tickLabelFill` property used in the `drawPolar...()` methods. Or is the Grid for the XYChart rendered somewhere else?

**Comment by wirew0rm** [comment]
May I ask which version you are using? When I paste the above snippet into chart.css i get blue tick labels.

The `GridRenderer` is rendering the grid (the dashed horizontal and vertical lines), the axes with its ticks, labels and tickLabels are rendered by the `Axis` implementation added to the chart, by default this is `DefaultNumericAxis`, but most of the styling and rendering parts happen in `AbstractAxisParameter`and `AbstractAxis` from which it is derrived.
There the style for the ticks gets set according to the property or the css when the ticks are calculated and the drawAxis routine draws each mark with it's individual style.

Also try to load the css as early as possible (and maybe try to zoom). Because the ticks are cached, there might be some rare cases where the cache is not invalidated when the style changes and so it is not reaplied.

**Comment by deepthought-64** [comment]
Guten Morgen, @wirew0rm. 

I am using the current version, `11.1.3`.

I have had no luck so far. I set the CSS on the chart right at the moment when i create it. But i also set the `-fx-tick-label-fill` directly in the code on the Axis object. Both have no effect. 
Also using Zoom to force re-creation of new tick marks has not helped.

I see that the tickMarkLabel is drawn in `drawTickMarkLabel()` in `AbstractAxis`. There you set `gc.setFill(tickMark.getFill());` but i have no real understanding of where the fill is set on the `TickMark`. I understand that it extends `Text` and therefore has a `fill` property, but i have failed to set that so far.

The only luck i had is if i extended the `DefaultNumericAxis` and overwritten the `getNewTickMark()`-method in which I set the fill on the returned `TickMark` manually. But I don't think that this should be the final solution :)

**Comment by wirew0rm** [comment]
Ok, this makes this easy, just update to 11.1.5, the getNewTickMark() method was missing the setFill on the TickMark, as you observed correctly. The corresponding issue #157 was fixed in 82ebf46a which is contained in the 11.1.5 release.

**Comment by deepthought-64** [comment]
Damn, that is then easy indeed. Thanks!!!
I did not see that there is a 11.1.5 out, i just used the version from the readme :)

Thanks for you help! If I can do anything in return, just tell me!

**Comment by wirew0rm** [comment]
No worries, glad it's working for you.
If you want to share your work on the dark theme, you could do a pull request for adding a `chart-dark.css` beside our default `chart.css` once you are satisfied with it. The topic pops up from time to time and it would be a good addition to chartfx.

**Comment by deepthought-64** [comment]
I am using [JMetro](https://pixelduke.com/java-javafx-theme-jmetro/#JMetro_a_Java_JavaFX_theme)'s dark theme, so the rest of the 'darkness' is not mine. I just added a css for the chart to look nice. 
But of course I will share my css when I am happy with my result. :)

**Comment by deepthought-64** [comment]
sorry guys that i bother you again. 
I am now trying the same with the legend label text fill and again having no luck. 

I saw in `DefaultLegend` that you use `LegendItem` which has the class `chart-legend-item` set on it.
But i was not able to set the color on the lable using 
```css
```

**Comment by deepthought-64** [comment]
Of course, an additional 5 minutes of thinking would have sufficed... got it.

```css
.chart-legend-item .text{
    -fx-fill: lightgrey;
}
```
did it! :)

**Comment by EasyG0ing1** [comment]
For anyone in the future looking at doing this, I accomplished it this way:

```Java
Platform.runLater(() -> {
    chart.lookupAll("*").forEach(node -> {
        String styleClass = node.getStyleClass().toString();
        if (styleClass.contains("tick-label") || styleClass.contains("axis-label")) {
            node.setStyle("-fx-text-fill: white; -fx-fill: white;");
        }
    });
});
```

**Comment by ennerf** [comment]
Here is a reference for the entire styleable hierarchy: https://github.com/fair-acc/chart-fx/blob/e4589c2c6ac0d345c2023dd50cc8f44d9686207a/chartfx-chart/src/main/resources/io/fair_acc/chartfx/chart.scss#L124-L167

for AtlantaFX:

```css
.chart .axis .axis-label, .chart .axis .axis-tick-label {
  -fx-fill: -color-fg-default;
}
```
