### ISSUE TITLE
Axes Do Not Resize on Maximize

### ISSUE THREAD

**Issue by samclark2015** [GSI-CS-CO/chart-fx#23]
When resizing via the maximize window button, the axes do not expand to fill the newly grown chart. Manual click-and-drag resizing works as expected.
Debugging shows that axes grow to expected maximized sizes when window is un-maximized. Furthermore, this can be replicated in the ErrorDataSetRendererSample demo.  

Initial chart sizes:
![Initial size of charts](https://user-images.githubusercontent.com/1639003/63186241-f2ba5280-c029-11e9-9d3f-4969b4d3b3d5.png)  
  
Charts after maximize (vertical axis did not grow):
![Charts after maximize (did not grow vertically)](https://user-images.githubusercontent.com/1639003/63186242-f352e900-c029-11e9-8400-0cd4a5d8055d.png)

**Comment by samclark2015** [comment]
Able to fix by wrapping `super.layoutChildren()` call in Chart.java in `Platform.runLater`.

Chart.java:1038 ... `Platform.runLater(() -> super.layoutChildren());`

**Comment by RalphSteinhagen** [comment]
@samclark2015 thanks for the bug-fix/recommendation. 
Will check whether this does not have adverse effects on the update performance for larger sets but otherwise merge this into master/JDK8.

**Comment by RalphSteinhagen** [comment]
JDK8-JavaFX bug: Issue resolved with merged workaround PR https://github.com/GSI-CS-CO/chart-fx/pull/24

@samclark2015 thanks again for the bug-fix hint. I traced the source to the Canvas size listener, where `requestLayout()` is not executed for JDK8-JavaFX. The line you mentioned worked but wasn't right because of performance issues for continuous/live updated.  I added the `Platform.runLater(() -> layoutChildren());` to the before-mentioned listener instead which seems to work nicely for JDK8 and is benign for JDK11+JFK12 where this isn't strictly needed anymore.

Hope this fixes your problem. Have a look at the 'master' and/or 'JDK8' branches. Re-open if necessary.
