### ISSUE TITLE
CrosshairIndicator plugin mouse handler reacts to mouse-over outside of the chart

### ISSUE THREAD

**Issue by deepthought-64** [GSI-CS-CO/chart-fx#238]
I use the `CrosshairIndicator` which registers and input event handler of type `MouseEvent.MOUSE_MOVED`.
The chart does not occupy the whole scene in my case and there can even be multiple charts in the scene.

What i can observe is that when i move the mouse inside the chart the eventHandler is invoked correctly (as ist should) but when i move the mouse in the upper left hand corner of the scene, it the handler is also invoked and it moves the cursor in all the graph(s):

![ezgif-7-37245ad1b6e0](https://user-images.githubusercontent.com/5528887/91068230-421b6180-e634-11ea-8f13-49581e81a60d.gif)

I think the reason is that the handler is not only registered to the node but also to the scene (in `addEventHandlers()` in `ChartPlugin`). I am sure that is done for a good reason so maybe there needs to be a level of filtering between the eventHandler in the Scene and the plugin?

Edit: I checked the source of the MouseEvent. Inside the graph it is `HiddenSidesPane@3f50cb28[styleClass=plot-content]` and the cursor is in the top-left it is `javafx.scene.Scene@6b51ec35`

**Comment by RalphSteinhagen** [comment]
@deepthought-64 thanks again for the MVP and reporting this. :+1: 

This issue didn't seem to pop up with the other plugins which have additional checks that prevent this.

The culprit seems to be in the [ChartPlugin](https://github.com/GSI-CS-CO/chart-fx/blob/4b93d58fc1f30434f6d8982376e1506203eeb99c/chartfx-chart/src/main/java/de/gsi/chart/plugins/ChartPlugin.java#L90-L101) which -- in addition to the actual node -- registers both mouse and keyboard events also to the scene. This is necessary for keyboard events but not strictly for the mouse. 

A simple filter that suppresses only `MouseEvent`-type events seems to work but we need to check whether there are other potential collateral effects ...

Thanks again for reporting!

**Comment by RalphSteinhagen** [comment]
@deepthought-64 thanks again for reporting, should be fixed now, and added the corresponding unit-test (see PR for details). Let us know if you can confirm the fix, we'll merge this to master and release this during the next opportunity.

**Comment by deepthought-64** [comment]
Hi @RalphSteinhagen 

thank you very much for taking the time to fix that. I have tested it against `fix-issues-231-238-SNAPSHOT` and it works as expected! 

One thing i am curious about: Why did you change `registerInputEventHandler(MouseEvent.MOUSE_MOVED, mouseMoveHandler);` to `registerInputEventHandler(MouseEvent.ANY, mouseMoveHandler);`? is it to capture a `MOUSE_EXITED_TARGET`-Event?

Thanks again for fixing this so quickly! :+1:

**Comment by RalphSteinhagen** [comment]
> is it to capture a MOUSE_EXITED_TARGET-Event?

Basically, yes. Will merge this then.

Enjoy and please consider sending us a screenshot of your application for our real-world use-case example.

**Comment by deepthought-64** [comment]
Ah okay, makes sense. :)

Will send it once it is finished (will still take a bit I assume). :)
