### ISSUE TITLE
horizontal white gaps in ScatterAndBubbleRenderer chart 

### ISSUE THREAD

**Issue by AmjadMoqade98** [GSI-CS-CO/chart-fx#267]
Hi, Dears,

First of all, plz allow me to say thank you for this library and to your effort at all.

I'm trying to draw a heat map chart same to the one on this image:
![hm](https://user-images.githubusercontent.com/48645435/94361733-49181280-00bf-11eb-87b9-862554cec1ce.PNG)

we have done this on the web before using canvas.

so I used the  ScatterAndBubbleRenderer chart here. 

What I actually did:

1- I'm receiving an array of (xAxis) values. for each x value, I have another set that simulates its (yAxis) values.
this is the output of drawing the given data, without applying the color schema. 
![os1](https://user-images.githubusercontent.com/48645435/94361863-0e62aa00-00c0-11eb-9a4f-770ab6924452.png)

2- Now to fill all the chart I used 200 points on xAxis and 200 points on yAxis = 40 000 total points
 I applied each point to an interpolation equation to interpolate colors values passed on the closest four corners from the data I have, as shown below :

![os3](https://user-images.githubusercontent.com/48645435/94362256-be391700-00c2-11eb-865d-473420189cda.png)

3- I got the following result

![os2](https://user-images.githubusercontent.com/48645435/94361985-dc9e1300-00c0-11eb-85ba-6321629b8103.png)

My Problem:

1- I'm always getting white horizontal gaps in the chart as below:
![os4](https://user-images.githubusercontent.com/48645435/94362432-e2e1be80-00c3-11eb-8de3-0f61390bb21a.png)

I tried to increase the number of data on the yAxis or decrease the distance between the points and it always runs to the same problem.

any suggestions? 

i also tried to use the ContourChart since it seems more reasonable to use to draw heatmap but it didn't work well for me since the chart wasn't drawing the points in the right positions as given in the xDim data and yDim data. 

any help will be highly appreciated. 
Regards!

code snippet : 
![image](https://user-images.githubusercontent.com/48645435/94362591-28eb5200-00c5-11eb-8f03-e6d1c41269c7.png)

this is almost the same thing I'm doing without the color and interpolation parts.

**Comment by RalphSteinhagen** [comment]
@AmjadMoqade98  have you tried the `ContourDataSetRenderer`? For large equidistant grid-type DataSet this usually yields better/faster results. There are parameters to control (or suppress) the interpolation when zooming in between defined data points. Other than that... w/o MVP it's a bit hard to assess what is happening.

**Comment by AmjadMoqade98** [comment]
@RalphSteinhagen  
Thank you so much.  i tried to use ContourDataSetRenderer and it worked like a charm.

this is the result I've got 

![image](https://user-images.githubusercontent.com/48645435/94380555-aef7af00-013e-11eb-8ee8-3f6db7099235.png)

now I'm trying to convert the y axis to a logarithmic axis using these properites 

        yAxis.setLogAxis(true);
        yAxis.setLogarithmBase(10);

but the data and yAxis labels disappeared after that as show below 

![image](https://user-images.githubusercontent.com/48645435/94380838-d602b080-013f-11eb-9ccd-8d407cfefe42.png)

any suggestions will be appreciated

**Comment by RalphSteinhagen** [comment]
@AmjadMoqade98  besides having '0' in the range (`log(0)` is not ideal when plotting on a real-valued x/y canvas) the basic ContourDataSetRenderer's low-level rendering relies on equidistant-data, thus uses direct calls to `gc.drawImage(image, xDataPixelMin, yDataPixelMin, xDataPixelRange, yDataPixelRange)`, and thus does not support logarithmic axes.  This for primarily performance reasons (aim: DataSets with around 2000x2000 points updating at 25 Hz) and also since we did not have a specific use-case that required logarithmic heatmap/contour plots.

However, this should be possible. Chart-fx deploys an MVC pattern and is specifically designed to be user-extensible, modifiable, and to be able to add new functionalities particularly `Renderer` (see also original [paper](https://github.com/GSI-CS-CO/chart-fx/blob/master/docs/THPRB028.pdf)).  

You'd need to either write your own custom `Renderer` or overwrite the existing `ContourDataSetRenderer`'s public `List<DataSet> render(GraphicsContext, Chart, int, ObservableList<DataSet>)` and then implement either a logarithmic GraphicsContext transform that is applied before the 'dawImage()' or generate a logarithmic-binned image that is drawn on the chart's `Canvas`.

Hope this helps and please feel invited to make a PR if you want to contribute to this particular feature.
