### ISSUE TITLE
How to change the Tooltip

### ISSUE THREAD

**Issue by RoWeigert** [GSI-CS-CO/chart-fx#268]
First of all,
chartfx is really fast compared to the original Oracle-Version.
But i simply can not find a way to change what is written in the Tooltips.
I tried to extend StringConverter<Number> and set it as Formatter, but nothing seems to change.

I want to have the posibilty to insert complete custom texts, so I can blend in error-messages in the measured values.

Regards,

Roland

**Comment by RoWeigert** [comment]
![wedge](https://user-images.githubusercontent.com/71972217/94366273-65c04480-00d7-11eb-9edd-e8c4dd918e6a.png)

**Comment by RalphSteinhagen** [comment]
@RoWeigert thanks for your interest in Chart-fx

The tool-tip text content is controlled by the return value of `DataSet::getDataLabel(int)` interface which for most `DataSet`s is modifiable via `DataSet::addDataLabel(int, String)` (and often also via a direct map-based access). N.B. you can define similarly a data point specific style via `DataSet::addDataStyle(int, String)` which can be used to change the marker, stroke colour, etc of that given point.

You may customise the default Tooltip look-and-feel via the CSS `chart-datapoint-tooltip-label` style-class controlling the `Label` (font, alignment, background, text colour, etc.) and modify the default text content formatting via:
```Java
final DataPointTooltip dataPointTooltip = new DataPointTooltip() {
    protected String formatLabel(DataPoint dataPoint) {
        return String.format("custom text:%n %s", dataPoint.getLabel());
    }
};
chart.getPlugins().add(dataPointTooltip);
```
N.B. we deliberately kept this ~~ugly~~ *unique* colour scheme reminiscent of the previous Swing-based version and also so that apt users feel more inclined to overwrite, define or contribute their own refined style. :smile: 

Let us know if this helps.

**Comment by RoWeigert** [comment]
Yes, 

this helps.
Now I can format everything in an easy way.
But I have on more question, that I wanted to find a solution for.

Is there a way, to set more than one XRangeIndicator-color, and set a height, that is not full chart.
This would even be a better solution to blend in errors. But since I plan to use those indicators also for  sample exists, i need them in more colors. I had a view with the charting-part of Oracle, but has significant speed-problems when there where thousands of points. Yours is by far faster.
![wedge (2)](https://user-images.githubusercontent.com/71972217/94516251-b3e35e00-0225-11eb-98b7-577b267c01a8.png)

**Comment by wirew0rm** [comment]
This is not possible at the moment the way the indicators are currently implemented.

You could however extend (or provide an alternative implementation for) the ValueIndicator classes, where you could change the layoutChildren routine to use other values instead of min/max in the [layoutLine call](https://github.com/GSI-CS-CO/chart-fx/blob/a73479c281ea3378dfb24f3c0dea0978bf2f08c6/chartfx-chart/src/main/java/de/gsi/chart/plugins/XValueIndicator.java#L91).

To use different colors you would have to expose the color property of the line/triangle/label nodes or bind them to your own color property.
Or you could modify the [style class](https://github.com/GSI-CS-CO/chart-fx/blob/a73479c281ea3378dfb24f3c0dea0978bf2f08c6/chartfx-chart/src/main/java/de/gsi/chart/plugins/XValueIndicator.java#L100) and have multiple style definitions in your css file.

Note however, that the indicator implementation uses javafx nodes, the use of which is one of the reasons for the scalability problems in the oracle implementation. So if you plan to have lots of errors in your dataset you might want to use `dataset.addDataStyle()` or a custom renderer which directly renders to the graphics context of the chart see e.g. the [LabeledMarkerRenderer](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/LabelledMarkerRenderer.java).

Allowing to set a color for each indicator separately seems like a nice feature and I think it would be a good pull request. For the height, I think does not really fit into the indicator (which as a UI element is derived from the UI of digital tabletop oscilloscopes). So it should probably be a separate plugin.

Hope this helps,

Alex

**Comment by RoWeigert** [comment]
Awesome,
your response time is really really fast.
I already extended the rangeindicator, and did an extra css-class for it, and calculate smaller sizes.
Seems to be the easiest solution.

There should not be too much of those errors in the chart. 
It is only important to see the charts "reaction" on events, that is why i implemented it.
Looks like I can completely switch over to your charting-library.

Keep on the really fantastic work.

Regards,

Roland

**Comment by wirew0rm** [comment]
Glad it worked out for you. We generally try not to limit the use of our library, but we're a relatively small team, so here and there you might have to implement or modify some feature yourself ;-)

I'll close this issue as it seems you found a way to get the behavior you want, but feel free to reopen if anything pops up or open other issues if you encounter anything else.
