### ISSUE TITLE
BarChart: Some bars are not displayed in v11.2.1

### ISSUE THREAD

**Issue by LaithBudairi** [GSI-CS-CO/chart-fx#275]
I have the following code of the bar charts I am drawing:

``` java
public class TestBarChart extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        double[][] data = {{-3, 1, 1}, {-3.1, 2, 1}, {-4, 3, 1}};
        double[][] data2 = {{19.2, 2, 1}, {18.7, 2, 3}, {17.9, 3, 3}, {17, 4, 3}, {16.8, 2, 3}, {15, 3, 3}, {14, 3, 3}};

        BarChart negativeChart = new BarChart("Negative Data");
        negativeChart.setResult(data);

        BarChart positiveChart = new BarChart("Positive Data");
        positiveChart.setResult(data2);

        HBox hBox = new HBox(negativeChart, positiveChart);
        VBox.setVgrow(hBox, Priority.ALWAYS);
        VBox vBox = new VBox(hBox);

        Scene scene = new Scene(vBox, 600, 400);

        primaryStage.setScene(scene);
        primaryStage.show();

        primaryStage.setOnCloseRequest(evt -> Platform.exit());
    }

    public class BarChart extends XYChart {

        final ErrorDataSetRenderer errorRenderer = new ErrorDataSetRenderer();
        private DefaultNumericAxis yAxes;
        private DefaultNumericAxis xAxes;
        private ChannelAnalysisResult result;

        public BarChart(String name) {

            super(new DefaultNumericAxis(""), new DefaultNumericAxis(" ", 0, 4, 1));

            // remove
            getPlugins().add(new Zoomer());
            setStyle("-fx-background-color: red");
            setTitle(name);
            titleLabel.setPadding(new Insets(0, 0, 0, 65));
            setPrefHeight(300);
            setPrefWidth(300);
            setHorizontalGridLinesVisible(false);
            setVerticalGridLinesVisible(false);
            setLegendVisible(false);

            xAxes = getXAxis();
            xAxes.setUnit(null);
            xAxes.invertAxis(true);
            xAxes.invertAxisProperty().setValue(true);
            xAxes.setMaxMajorTickLabelCount(5);
            xAxes.setMinorTickVisible(false);
            xAxes.setAutoRanging(true);

            yAxes = getYAxis();
            yAxes.setUnit(null);
            yAxes.setAutoRanging(false);

            errorRenderer.setPolyLineStyle(LineStyle.NONE);
            //errorRenderer.setMarkerSize(1);
            errorRenderer.setDrawMarker(false);
            errorRenderer.setErrorType(ErrorStyle.NONE);
            errorRenderer.setDrawBars(true);
            errorRenderer.setDynamicBarWidth(false);
            errorRenderer.setBarWidth(1);
            errorRenderer.setPointReduction(false);

        }


        @Override
        public DefaultNumericAxis getXAxis() {
            return (DefaultNumericAxis) super.getXAxis();
        }

        @Override
        public DefaultNumericAxis getYAxis() {
            return (DefaultNumericAxis) super.getYAxis();
        }


        public void setResult(double[][] result) {

            final DefaultErrorDataSet dataSet = new DefaultErrorDataSet("dataSet_Default");
            dataSet.clearData();
            dataSet.setStyle("fillColor=rgb(0,0,0); markerColor=rgb(0,0,0);");


            for (int i = 0; i < result.length; i++) {

                dataSet.add(result[i][0], result[i][1]);

                if (result[i][2] == 1.0) {
                    dataSet.addDataStyle(i, "index=" + i + "; fillColor=rgb(3,103,219); markerColor=rgb(3,103,219);");
                } else if (result[i][2] == 2) {
                    dataSet.addDataStyle(i, "index=" + i + "; fillColor=rgb(128,128,128); markerColor=rgb(128,128,128);");
                } else {
                    dataSet.addDataStyle(i, "index=" + i + "; fillColor=rgb(0,0,0); markerColor=rgb(0,0,0);");
                }
            }
            errorRenderer.getDatasets().clear();
            errorRenderer.getDatasets().addAll(dataSet);
            this.getRenderers().setAll(errorRenderer);
        }
    } }
```

When I run this code this is how my charts are drawn:

![case 0](https://user-images.githubusercontent.com/69572447/95739316-532b3b00-0c93-11eb-9f69-0b4a182389ef.png)

Note that not all the bars are displayed. Also note that the tick label -4.00 in the left chart is not fully displayed which explains why the last bar is not displayed as well. So what I did is adding this line of code `dataSet.add(0,0);` and this is how are my charts are drawn:

![case1](https://user-images.githubusercontent.com/69572447/95739477-95ed1300-0c93-11eb-9d46-a2998f7b4b3f.png)

As you can see all the bars on the left chart are displayed. Now if we replace the line I added previously with this one `dataSet.add(20,0);` then this is how the charts are drawn: 

![case2](https://user-images.githubusercontent.com/69572447/95739570-b5843b80-0c93-11eb-972a-9228d4b5cc73.png)

As you can see all the bars on the right charts are displayed as well as on the left one, but it seems that when the x distance between bars is very low then they overlap each other which may explain why the charts on the right were not distinguishable from each other.

I'm not sure why this happens, it's like the data are not fit in the bar chart in most cases. I'm not trying to use the zoom feature to see the bars. I just want all the bars to be displayed correctly when I draw them the first time. Is there any better workaround to handle this issue ?

**Comment by wirew0rm** [comment]
Hey Laith,

thanks for your interest in our library and for the detailed bug report.

I guess there are multiple issues here:
- The axes being cut of on the right: this looks like some layouting bug, can you try to use another javafx container and maybe only show one of the plots for testing? Most of the samples use StackPane or BorderPane as the root pane. Then we can look into why it does not work in your case. Can you also try to change the width of your window and check how that influences this bug? And also the `setPrefWidth()` calls?
- Not all bars being drawn in the right chart: By default, the renderer assumes, that data is sorted ascending. It then filters the data to include only data from the point before the first inside the axis range to the first one outside of it. It does this by doing a binary search for the axis min and axis max, which does not work correctly if your data is not sorted and consequently not all points are plotted. You can work around this by either sorting your data or by setting `renderer.setAssumeSortedData(false)`. The second one will degrade performance if you zoom into datasets with a large number of points, since it will disable PointReduction and process every point even if they are not in the visible range.

Some remarks on the rest of the code:
- Please keep your code samples minimal or try to reproduce the bug by modifying one of our samples. This makes it a lot easier for us to understand what's going on. E.g. the style code and a lot of the renderer settings are not necessary to reproduce your problem.
- The way you update your dataset might become slow for a huge number of points. If you want to create a new DataSet for each update, I recommend to use the DataSetBuilder or at least to disable listener notification for each added point. Also the dataset.clear() and the renderer.setAll calls are unnecessary. The other way would be to modify the data in the existing dataset (surrounded by a `lock().writeLockGuard()`). Just take a look at the samples for how this works.

Hope this helps,

Alex

**Comment by LaithBudairi** [comment]
Hi Alex,

Thanks for your reply, `renderer.setAssumeSortedData(False)` helped me solve the issue. 

I tried setting the width for the chart and axes but the -4.00 still not fully displayed.

Thanks for the heads up regarding the DataSetBuilder,

Laith
