### ISSUE TITLE
JavaFX process doesn't end

### ISSUE THREAD

**Issue by Jhok2g** [GSI-CS-CO/chart-fx#279]
Hi, I'm experiencing an issue where the main process won't end after clicking the close button, and this only happens when the line 
`XYChart chart = new XYChart(xAxis1, yAxis1);`
is called. (if i comment that line the stop() method of the main app is called just fine)
Any idea why this is happening? Here is the method where the chart creation happens. (It's the initialize() method from the scene controller)

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        this.model = App.getModel();

        cFecha.setCellValueFactory(new PropertyValueFactory<>("fecha"));
        cHora.setCellValueFactory(new PropertyValueFactory<>("hora"));
        cPeso.setCellValueFactory(new PropertyValueFactory<>("peso"));
        cAcum.setCellValueFactory(new PropertyValueFactory<>("acum"));

        ObservableList<Pesada> pesadas = model.getPesadas();
        tableView.getItems().addAll(pesadas);

        DefaultNumericAxis xAxis1 = new DefaultNumericAxis("time", "iso");
        xAxis1.setOverlapPolicy(AxisLabelOverlapPolicy.SKIP_ALT);
        DefaultNumericAxis yAxis1 = new DefaultNumericAxis("y-axis", "a.u.");

        XYChart chart = new XYChart(xAxis1, yAxis1);
        chart.legendVisibleProperty().set(true);
        chart.getPlugins().add(new DataPointTooltip());
        chart.setAnimated(false);

        xAxis1.setAutoRangeRounding(false);
        xAxis1.setTimeAxis(true);
        yAxis1.setAutoRangeRounding(false);

        DefaultErrorDataSet dataSet = new DefaultErrorDataSet("Pesadas");

        for(Pesada p : pesadas){
            dataSet.add(p.getTimestamp(), p.getAcum());
        }

        chart.getDatasets().add(dataSet);
        box.getChildren().add(chart);
    }

Also, the issue happens even if the chart is not added to the scene

**Comment by Jhok2g** [comment]
Nevermind, adding
`stage.setOnCloseRequest(evt -> Platform.exit());`
to the start method solved it. Why does this happen? Is the chart somehow consuming the closeRequest event when that line is not added?

**Comment by RalphSteinhagen** [comment]
@Jhok2g  Nope. That is the expected and documented [JavaFX](https://docs.oracle.com/javase/8/javafx/api/javafx/application/Platform.html) behaviour depending on whether [`Platform.setImplicitExit(boolean)`](https://docs.oracle.com/javase/8/javafx/api/javafx/application/Platform.html#setImplicitExit-boolean-) is set to `true` or `false`. 

You typically need this, for example, if you want a controlled termination of other tasks on exit or if all the other threads are [daemon](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDaemon(boolean)) threads. Otherwise, the application will either hang forever, shut down right after it is initialised, or crash other threads/io tasks that have not properly stopped.

**Comment by RalphSteinhagen** [comment]
@Jhok2g did this answer your question?

**Comment by RalphSteinhagen** [comment]
closing since this seems to have been solved and because of no further activity. Please feel free to re-open if you feel that this is a bug.
