### ISSUE TITLE
hashCode function on DataSet return different results after each value addition

### ISSUE THREAD

**Issue by tanrikut** [GSI-CS-CO/chart-fx#325]
Hi,

Following code produces different results on each call to hashCode function:
```java		
                DoubleDataSet data = new DoubleDataSet("ABC");
		System.out.println(data.hashCode());
		data.add(1.0, 2.05);
		data.add(2.0, 6.05);
		System.out.println(data.hashCode());
		data.add(3.0, 6.05);
		System.out.println(data.hashCode());
```

But according to general contract of hashCode in Java:

> Whenever it is invoked on the same object more than once during an execution of a Java application, hashCode() must consistently return the same value, provided no information used in equals comparisons on the object is modified. This value needs not remain consistent from one execution of an application to another execution of the same application

This makes it impossible to use DataSet classes inside HashTable etc.

**Comment by pacher** [comment]
Why not just use `IdentityHashMap` instead of `HashMap` since DataSet is mutable?

**Comment by tanrikut** [comment]
Well, I didnt know about IdentityHashMap but it will do the trick. Thanks.
But still hashCode doesnt obey the general contract.

**Comment by pacher** [comment]
It does if `equals` is overridden to perform content-base "deep" comparison, which is a common practice for data structures in java.

Imagine two datasets containing the same points, what should `dataset1.equals(dataset2)` return? It is customary to override equals and perform deep comparison so that it will return `true`, which is what I assume the authors of the library did.
Now if you add points to dataset1, then it is no longer equal to dataset2, isn't it? So it must have a different hashcode per contract.

It is mentioned clearly in the `Map` javadoc:
> Note: great care must be exercised if mutable objects are used as map keys. The behavior of a map is not specified if the value of an object is changed in a manner that affects equals comparisons while the object is a key in the map.

Since Dataset is mutable, it should generally be used as a map key. And identity-based data structures exist for this case.

**Comment by wirew0rm** [comment]
Hey there,

as @pacher suspected/pointed out, equals is indeed overridden to take the dataset's points into account. This is also mentioned in section quoted from hashCode's contract:

> But according to general contract of hashCode in Java:
> 
> > Whenever it is invoked on the same object more than once during an execution of a Java application, hashCode() must consistently return the same value, **provided no information used in equals comparisons on the object is modified**. This value needs not remain consistent from one execution of an application to another execution of the same application

I will close this issue for now as op's problem at hand as well as the fundamental issue seems to be resolved, feel free to comment/reopen if you disagree.
