### ISSUE TITLE
Intellij: Error Resolving classes inside the chartfx-chart - StyleParser

### ISSUE THREAD

**Issue by raven2cz** [GSI-CS-CO/chart-fx#354]
I found the problem that I cannot resolve classes inside the chartfx-chart like StyleParser. This happens with intellij environment. 
I tried to clean whole project, change all things many times, but the result is still same. Linkage error inside the same submodule!
I found the problem that your trick in pom.xml doesn't work correctly:
`<version>${revision}${sha1}${changelist}</version>`
where the revision is master.
This doesn't work for me in my environment. If I change it to correct syntax like 11.2.0-SNAPSHOT, all works correctly after that.
Is there some prepare-environment steps now?

**Comment by wirew0rm** [comment]
The one problem I know of is that intellij's maven implementation does not resolve plugins from the parent pom. If you use an existing version number, it will resolve the plugin from the repositories, but with the branch based version number it will only work if you install the plugin into your local .m2 repository once using `mvn install` from the command line.

What you might be seeing is that mvn tries to build the project, but because the code-generation plugin is missing some auto generated classes will be missing.

**Comment by raven2cz** [comment]
StyleParser is independent on the libraries. And mvn clean install I'm using always. I have all auto generated classes etc. The main problem is just StyleParser. This is another type of problem. How long is there this change with master instead of the valid version? I have this problem after using actual master branch.

**Comment by wirew0rm** [comment]
The change is from 18th Dec: 5455e61f

I tried to reproduce, removing `rm -r .m2/repositories/de/gsi`, doing a fresh checkout and importing that into intellij after "Invalidate Caches...". First complains about missing plugin, doing `mvn install` once solves those and no errors in intellij. I'm on an older intellij provided by my distribution, but I have a recent one at home where didn't notice any problems.

Could you provide the error messages for the issues you are seeing?

**Comment by raven2cz** [comment]
It seems that the problem was in the corrupted jar file in the local m2 repository. After deleting the local de/gsi in m2 the StyleParser is correctly found. 
So, this helps:
`rm -r .m2/repository/de/gsi`
Alexander, thanks for help!
