### ISSUE TITLE
Error using Zoomer Plugin - javafx.controls does not export com.sun.javafx.scene.control.behavior

### ISSUE THREAD

**Issue by nkoding** [GSI-CS-CO/chart-fx#409]
**Describe the bug**
Hi, 

I've set up a JavaFX project and load the chart-fx dependency via maven.
In my chart class I'm using the Zoomer plugin like this:

`chart.getPlugins().add(new Zoomer());`

Without the zoomer plugin everything works fine. But with it I encounter the following error:

```
java.lang.IllegalAccessError: superclass access check failed: 

class impl.org.controlsfx.behavior.RangeSliderBehavior (in module org.controlsfx.controls)
 cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) 
 because module javafx.controls 
 does not export com.sun.javafx.scene.control.behavior 
 to module org.controlsfx.controls
```
I've tried the VM-Args mentioned in Issue #6 and added this directive:
```
--add-opens
javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED
```

Also while trying stuff I found out that the modules javafx.fxml and javafx.web are producing those errors:
java.lang.module.FindException: Module javafx.web not found
java.lang.module.FindException: Module javafx.fxml not found

So I removed them and dont get the "not found"-errors anymore. 

Unfortunately the IllegalAccessError still persists.

Any help would be very appreciated.
Thanks in advance!

**Environment:**
 - OS: Ubuntu 20.04
 - Java version: 11
 - JavaFx version: 13
 - ChartFx version: 11.2.5

**Comment by wirew0rm** [comment]
Hey,

the vm arguments are slightly different depending on which dependencies end up on the module path vs the classpath. If you read the error message, it mostly corresponds to the missing/incorrect vm argument.
In your case this should be `--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls`.
Since the option stems from our controlsfx dependency I will also refer you to their [wiki page about debugging jpms dependency problems](https://github.com/controlsfx/controlsfx/wiki/Using-ControlsFX-with-JDK-9-and-above#understanding-exceptions).

I'll try to update the README with more up-to-date parameters, but there will probably be corner cases where you have modify them. Thankfully, once you figured out how to read the exceptions, that is pretty straightforward.

I hope this helps,

Alex

**Comment by wirew0rm** [comment]
I updated the [corresponding section in the README.md](https://github.com/GSI-CS-CO/chart-fx/blob/81ef5de3f01a1fad21b626d9f705c5d9a3f1a048/README.md#javafx-jvm-command-line-options) (still in PR).

Were you able to fix your problem?

**Comment by wirew0rm** [comment]
I assume that this problem is fixed by using the correct java module system command line arguments. Feel free to reopen if the problem persists or if you see a way for us to make this easier to configure.
