### ISSUE TITLE
WatchValueIndicator: css styling

### ISSUE THREAD

**Issue by domenicquirl** [GSI-CS-CO/chart-fx#427]
**Describe the bug**
When styling the chart with JavaFX CSS, I can't get the `value-indicator-label`, `value-indicator-line`, `value-watch-indicator-label`, `value-watch-indicator-label` or their indexed variants to apply. If I subclass the respective `YWatchValueIndicator` and similar and assign IDs to line and label with `setID`, referencing these classes in the CSS does give the expected result with the CSS applied. Other classes like `chart-plot-background` are working as expected.

Also, the data value shown by `YWatchValueIndicator` appears _below_ the marker triangle, like so: 
![misaligned value](https://user-images.githubusercontent.com/28535538/120994714-0990e280-c785-11eb-86e9-72c62d4cf0b3.png)

With coloured `label`:
![with label box](https://user-images.githubusercontent.com/28535538/120994583-e8c88d00-c784-11eb-8fc6-9c5ab7d97ff4.png)

**To Reproduce**
The indicator is added through a UI interaction to `chart.getPlugins()`. The CSS file is added to the JavaFX scene as a stylesheet.

**Environment:**
 - OS: Windows
 - Java version: AdoptOpenJDK 15.0.2.7-hotspot
 - JavaFx version: OpenJFX 15.0.1
 - ChartFx version: `charfx-chart` 11.2.2 and 11.2.5 (I upgraded to check if it's a version thing)

**Comment by wirew0rm** [comment]
Hey,

thanks for reporting this, I actually have a modified version of the indicator, which allows css restyling, but which I have not tested against the samples in chartfx. If you want you can add it into your own code as a workaround until it gets fixed in chart-fx: https://gist.github.com/wirew0rm/43bc8c1b2e29bbbcdd4cf271cb38a917

cc @raven2cz: Do you want to take a look at this? You probably have more usages of the plugin. If not, I would make a PR with my modified version and ask for your review there.

**Comment by domenicquirl** [comment]
Hi, thanks for the response!
How exactly does your version differ in the CSS handling? From looking at it, it seems to set the same style classes as [here](https://github.com/GSI-CS-CO/chart-fx/blob/a3630e3cf77ca826bf19428df9c24f1ead661271/chartfx-chart/src/main/java/de/gsi/chart/plugins/YWatchValueIndicator.java#L187), which I checked do get applied with both versions.

Indeed, the (non-)styling is the same in both cases, this is your modified version plugged in:
![image](https://user-images.githubusercontent.com/28535538/121029701-1cb5a980-c7a9-11eb-99db-62ddad402cc0.png)
The label position appears to be more centred in this version, though still not quite (maybe padding or something about the baseline offset that is used in the in-tree version?). From some quick testing, the y position seems to be off by about 3/4 of the baseline offset, though that may be a coincidence.

Another issue seems to be the width of the indicator not adapting to the content of the label (label highlighted with border):
![image](https://user-images.githubusercontent.com/28535538/121032620-b8e0b000-c7ab-11eb-9539-ac9d23f1e51e.png)

This is fixed with the modified version's `width` and `halfHeight` calculations in `layoutChildren`. Image with styling through IDs, y position adjustment and width based on the label: 
![image](https://user-images.githubusercontent.com/28535538/121035195-ed556b80-c7ad-11eb-99cb-4527b7c328c2.png)

**Comment by domenicquirl** [comment]
Also I'll briefly re-iterate that this applies to both named indicators `XYValueIndicator` as well as axis value indicators `XYWatchValueIndicator`. I'll attach some pictures of the former as well.

With(out) the style classes:
![image](https://user-images.githubusercontent.com/28535538/121036178-da8f6680-c7ae-11eb-9170-a825f54ae0c8.png)

With IDs:
![image](https://user-images.githubusercontent.com/28535538/121036691-280bd380-c7af-11eb-879d-23efea2060e6.png)

(featuring mismatched tick marks, but let's ignore that for now)

**Comment by wirew0rm** [comment]
Sorry, seems like I read over some parts there because it sounded familiar to the problem I had. Thanks for the detailed analysis.
I also had problems applying the css, im not sure if it is the root of your problem as well, but the way the css preference rules are and the chart is set up, if a css selector exists in chartfx's chart.css file, it will override the css in the users scene stylesheet. I think this could be fixed by adding chart.css as a UserStyleSheet, but I'm not completely sure about that. Anyway, removing the stylesheet from chart (`chart.getStylesheets().clear()`, and readding the needed parts to the scene stylesheet) can work around that (it looks like you are overriding most styles anyway).

**Comment by domenicquirl** [comment]
Ah, [the `Chart` constructor setting the stylesheet](https://github.com/GSI-CS-CO/chart-fx/blob/cd202c7c9a0b40f1e66b6d0fe8fd93fffbec5435/chartfx-chart/src/main/java/de/gsi/chart/Chart.java#L328) on the chart must make that take precedence over the scene's stylesheets. I'd like to keep the more layout-related parts of the default CSS, but it looks like I can make my CSS take precedence again by also threading it through and setting it on all the charts in addition to the scene. Thanks a lot for clearing that up!

**Comment by domenicquirl** [comment]
To summarize, I overrode `YWatchValueIndicator`'s `layoutChildren()` to include the `triangle` width and height calculation from @wirew0rm's modified version of the indicator. Further, 
```java
@Override
protected void layoutWatchLabel( Bounds bounds, double axisPos, boolean isRightSide ) {
  super.layoutWatchLabel( bounds, axisPos, isRightSide );
  this.label.setTranslateY( -3 * label.getBaselineOffset() / 4 );
}
```
moved the displayed y-axis number value back onto the marker.
