### ISSUE TITLE
Jumping x axis

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#43]
I keep hitting cases where the x-axis becomes very difficult to read because the axis labels keep "jumping", i.e., every half a second the labels change from [1,2,3,4,5, etc.] to [1.5,2.5,3.5,4.5,etc.].

Here is a video of what I mean: https://youtu.be/RNTAVZD_PDs

I've tried playing around with the tick units, but they don't seem to make a difference. Is there anything else I can do?

**Comment by wirew0rm** [comment]
You could switch to a different AxisLabelOverlapPolicy, the default is SKIP_ALT, which leads to the "jumpy" behaviour you observe.

Try `chart.getXAxis().setOverlapPolicy(AxisLabelOverlapPolicy.DO_NOTHING)`.
(this will of course lead to overlapping labels, but you might be able to prevent that, e.g. by rotating the labels)

It would be nice to have label positioning more consistent, right now it just checks if the labels are overlapping and just alternately shows and hides them.
Maybe this could be archieved by initializing the counter with the `(fistTIck modulo unit) modulo 2`?
The code in question is here:
https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.1.0/chartfx-chart/src/main/java/de/gsi/chart/axes/spi/AbstractAxis.java#L1058-L1093

**Comment by ennerf** [comment]
The `DO_NOTHING` policy actually worked pretty well as is on Windows, but resulted in a lot of overlap on Linux. I found that most of my issues are related to decimal points, so I was able to fix it with a custom string converter that ignores any non-integer values.

Thanks again

**Comment by RalphSteinhagen** [comment]
N.B. don't discount the other [AxisLabelOverlapPolicy](https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.1.0/chartfx-chart/src/main/java/de/gsi/chart/axes/AxisLabelOverlapPolicy.java) options and/or changing the font (e.g. fixed-width). Otherwise providing another String converter is also a valid option as suggested. 

As a side note:
The generic handling of overlapping labels (and appropriate decimal points, large/small exponentials, time ...) is not quite trivial. This is one of the reasons why we used the ICU-based decimal converter and are a bit hesitant to change the code since there are so many use-cases affected and we didn't want to customize each and every one of them.

However, if you find a more suitable/general/flexible solution: please let us know. I'd be happy to give it a review and incorporate into the mainline branch.
