### ISSUE TITLE
Noisy data signal leads to poor rendering performance

### ISSUE THREAD

**Issue by dedeibel** [GSI-CS-CO/chart-fx#499]
I noticed unexpectedly bad performance in some real world cases. It turns out those cases were noise signals with a large y value difference on a point to point basis. Please see the screenshot. On my machine it takes about **3 seconds** to render the chart of **100k** values.

I create a dump of the real world data and created a sample chart which can be seen in branch [`bpeter-noisy-signal-performance-example`](https://github.com/GSI-CS-CO/chart-fx/tree/bpeter-noisy-signal-performance-example)

You can start the timer using the button and look for the console output `"flatline: false. update done"` and start counting the time until the noisy signal is displayed.
(It alternates between a flat line and the noisy signal)

![Screenshot at 2022-03-18 08-54-39](https://user-images.githubusercontent.com/26708/158961062-0cfa2ef2-f94c-462b-b760-8f926dc7b456.png)
 
**Environment:**
 - OS: debian 11.2
 - Java version: 11.0.14 OpenJDK
 - JavaFx version: 13.0.1
 - ChartFx version: master

Are there any ideas on how to mitigate or solve this?

**Comment by ennerf** [comment]
You are probably running into less efficient data set reduction. Points that are within N pixels are combined into one, so a noisy signal ends up doing a lot more drawing calls than a flat line.

**Comment by RalphSteinhagen** [comment]
Have you tried
* w/o data reduction, 
* smaller/larger min-pixel-distance, and/or 
* (less correct but more efficient) down-sampling?

That should give an indication of whether it's in the renderer, DataSet, and/or data reduction algorithm.

**Comment by dedeibel** [comment]
[chartfx-noise-test-runs.zip](https://github.com/GSI-CS-CO/chart-fx/files/8334840/chartfx-noise-test-runs.zip)

Whole logs.

**Comment by RalphSteinhagen** [comment]
@dedeibel had an in-more-depth look at your problem. 

While the DataSet you provided is certainly challenging (i.e. small x-data point distances that would be squashed onto the same x coordinate/pixel if it weren't for the large y variations) this is not a bug.  The DataSet is drawn scientifically correct, and the `DefaultDataReducer` faithfully reduces the points based on their previous-next pixel distance using the [Manhatten norm](https://en.wikipedia.org/wiki/Norm_(mathematics)#Taxicab_norm_or_Manhattan_norm) while still preserving individual outliers.

On my machines, the initial data points are reduced from 100k to some 67k data points within less than 2 milliseconds for the `DefaultDataReducer` and to about 17k data points for the `RamanDouglasPeukerDataReducer` within about 100 milliseconds. The [Ramer–Douglas–Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) is used in other libs but not necessarily ideal in terms of data reduction accuracy and real-time use. The bottleneck appears to be rather in the JavaFX backend, more specifically, in the (unfortunately) inaccessible internals of the `QuantumRenderer` and poly-line implementation: notably the `GraphicsContext::strokePolyline(...)` and `GraphicsContext::strokeLine(...)` within the `Canvas` interface.
This is/has been known and most of the DataReducer/caching infrastructure is about avoiding/minimising the need/effort for these two functions because they seem to be internally computed in software and not forwarded to the underlying GPU.

As a workaround, you may, for example, choose to:
  * draw only markers (best performance, best accuracy) <-- this would be my recommendation,
  * use the `RamanDouglasPeukerDataReducer` (qualitatively pleasing but scientifically suspicious/inaccurate), or
  * implement your own data reduction and/or a new `DataReducer` implementation.
 
Most of the other schemes we looked at (earlier and now) are either numerically expensive (i.e. one wouldn't gain much in terms of drawing performance) and/or lose w.r.t. scientific precision/rigor (e.g. simple down-sampling). 

The best -- presently unattainable solution -- would be to open up and improve the internal graphics stack of JavaFX and, for example, forward the poly-line (and other) primitives directly to the underlying OpenGL/Metal/Vulkan/... backend. That's also the solution many 'immediate mode UI' frameworks seem to go...

**Comment by dedeibel** [comment]
Thank you for your analysis and suggestions :+1:. I will close this now.

Detecting the noise situation or finding a good reduction algorithm for this case would be great but since my situation has to handle a great deal of different use cases makes it hard to infer what the user wants to see. I fear it will also require a way for the user to configure the behaviour interactively.
