### ISSUE TITLE
Add default implementation for DataSet2D::get

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#59]
`DataSet` has methods `get(int dim, int index)` and `getIndex(int dim, double value)`.

`DataSet2D` provides a default implementation for `getIndex`, but not for the `get` method. It'd be nice if that were added as well.

I tested #58 and haven't checked the develop branch.

**Comment by wirew0rm** [comment]
I'm not really sure what a default implementation of get should do, as the access to the data depends on the implementation of the DataSet.

The getIndex method is different as it only accesses the data using methods from the DataSet2D interface.

Could you clarify on this?

**Comment by ennerf** [comment]
I thought this was an oversight, but apparently it used to be

```Java
@Override
default double get(final int dimIndex, final int index) {
  return dimIndex == DIM_X ? getX(index) : getY(index);
}
```

and was deliberately deleted in [3d8e39d](https://github.com/GSI-CS-CO/chart-fx/commit/3d8e39d).

What was the reason for this? The existing implementation looks sensible for `DataSet2D`.

**Comment by RalphSteinhagen** [comment]
We switched from the specif 2D and 3D DataSet interface to a more generic, stream-line one that does less distinction inside the lib whether the data is 2D, 3D or for that matter 1D or multi-dimensional. 

This way one is able to loop through the dimension and to simplify some of the common algorithms for 2D/3D/... N-D which significantly reduces (nearly a factor '2' :smile: ) the amount of custom code one has to test/nurture.
However, while trying to avoid using specific 2D/3D APIs in the lib, we decided to keep the 2D and 3D interface for the lib users, since some may prefer to have an explicit `getX(index)` rather than `get(DIM_X, index)` for semantic reasons. 
The last x.1.0 change was big (for us), unfortunately, we couldn't keep some of these convenience default implementations in all cases because they caused circular dependencies, but hope that the change was for the better.

Our DataSet usage assumption was/is that 
1. most users use one of the provided default DataSet implementation (e.g. `DoubleDataSet`, `DoubleErrorDataSet`, ...),
2. few developers (that find some functionality lacking) to derive from one of the 'AbstractDataSet' classes that take care of most of the less performance-critical boiler-plate code (such as locking, notification, meta-data handling etc.), and 
3. the pure `DataSet` and `DataSetError`interface for those that already have a data container and want to simply expose their existing data to the lib and/or find better, faster, smarter implementations than the above. 

Please feel free to share/add feature requests to our tracking issue #44 and/or to contribute code if you. We'd be happy to integrate this into the lib for everybody else. 

N.B. We are starting to integrating more and more n-dimensional data and you may have seen that we started adding datasets that either integrate and/or provide projections from n-dimensional data to 2D/3D data visualisations.

**Comment by RalphSteinhagen** [comment]
@ennerf may we close this issue, or is there something that should be fixed?
