### ISSUE TITLE
Error when "mvn exec:java" at dataset

### ISSUE THREAD

**Issue by minosniu** [GSI-CS-CO/chart-fx#62]
> Could not find artifact de.gsi.dataset:chartfx-dataset:jar:11.1.0-SNAPSHOT

I've tried many JDK versions, along with various sequences of compiling. The error sticks with the above error message about dataset. 

MacOS Catalina 10.15.1
OpenJDK 11.0.2
Intellij IDEA 2019.2
Maven 3.6.1

**Comment by RalphSteinhagen** [comment]
Without a 'pom.xml` this is a bit hard to diagnose. Did you try:

```bash
git clone https://github.com/GSI-CS-CO/chart-fx.git
cd chart-fx/
mvn compile install
mvn exec:java
```

The `mvn install` is important in this instance if you want to run the examples outside an IDE since the snapshots are not deployed to maven central (only the official releases) but only to the staging area. The `mvn install` pushes this into your local `.m2/...' cache. 

Enjoy!

**Comment by minosniu** [comment]
$mvn install did not solve the problem. However I managed to bypass the problem by disabling javadoc. Tried "mvn clean install -Dmaven.javadoc.skip=true" and saw all the demos.
