### ISSUE TITLE
Candlestick chart

### ISSUE THREAD

**Issue by petrov9** [GSI-CS-CO/chart-fx#64]
Is it already exists in project, or something similar ?

**Comment by RalphSteinhagen** [comment]
Hi Anton,

thanks a lot for your interest in using our little chart lib. We haven't got a dedicated [candlestick](https://en.wikipedia.org/wiki/Candlestick_chart) renderer yet since this has not (yet?) been part of our core use case. However, if you like to contribute one, I am happy to integrate this for you into our little library. 

There are already a lot of the necessary sub-components implemented in the [ErrorDataSetRenderer](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/ErrorDataSetRenderer.java). However, I would not recommend extending this due to its complexity and primary focus on the scientific use-case (marker, error-bars/-surfaces, etc.) but starting a new (copy? 'CandleStickRenderer'?).

The [LineRenderer](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/LineRenderer.java) might also be a good (much easier) starting from which you could extend and/or copy part of the functionality from the other renderer that you like and need.

I'd also recommend deriving a new DataSet-derived type (+ Enum, CandleStick Interface) and one default DataSet implementation and sample alike to the [DoubleErrorDataSet](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-dataset/src/main/java/de/gsi/dataset/spi/DoubleErrorDataSet.java) so that we can test/maintain/test-case this long-term. As a suggestion for the DataSet: the first dimension should be time and the additional dimensions attributing to the open/close/high/low/(...?) values. This way you should also see results if somebody attaches the DataSet to another non-CandleStick aware renderer. A good abstract interface definition is always useful, because others may want to choose to simply wrap the interface around their existing data structure (ie. DB callback objects, etc.). At least that was our observation internally and with other labs.

Hope this helps and gets you started. Let me know if you have further questions on this or the mechanics of the chart-fx library.

**Comment by petrov9** [comment]
I did not the best realization. But it's work. Will create pull request later.

Double Histogram:
![image](https://user-images.githubusercontent.com/28570170/71410793-bd68e580-2657-11ea-9db8-edbf7cb6bab1.png)

Candle stick:
![image](https://user-images.githubusercontent.com/28570170/71410828-dbcee100-2657-11ea-80b8-142f03f64a3c.png)

**Comment by RalphSteinhagen** [comment]
@petrov9 the first visual impression looks good. 

I am unfamiliar with the 'Double Histogram', so I cannot comment on this.

Two suggestions regarding the 'candle stick' renderer:
1. maybe add more month, or year/months, or a time axis to the horizontal axis in the sample
2. add maybe (optional) dashes on the bottom/top of the low/high vertical lines so that they are more easily distinguished from the vertical grid lines.

Am looking forward to the DataSet definition you chose.

Keep up the good work! Cheers, Ralph

**Comment by selamiwork** [comment]
> I did realization, but it's not too good, it was fast way. But it's work. Will create pull request later.
> 
> Double Histogram:
> ![image](https://user-images.githubusercontent.com/28570170/71410793-bd68e580-2657-11ea-9db8-edbf7cb6bab1.png)
> 
> Candle stick:
> ![image](https://user-images.githubusercontent.com/28570170/71410828-dbcee100-2657-11ea-80b8-142f03f64a3c.png)

Hi, did you finish the candlestick renderer ? if you share the source code, it will be very pleasure ?

**Comment by RalphSteinhagen** [comment]
@petrov9 what's the status of this? The teasers are quite nice. Are you still planning a PR? 

We will be moving/starting soon with the move to the new x.2.y API (see #44)

Looking forward!

**Comment by RalphSteinhagen** [comment]
@petrov9 any update on a possible PR or would you like to keep the mod private? 

We are working on the next minor release right now and now would be a good opportunity to merge this.

**Comment by RalphSteinhagen** [comment]
@petrov9 would you be willing to do a PR for this? I saw that you already worked on this in your private fork but didn't want to do a pull of your work without your consent... let us know. We'd be happy to incorporate this and complete the testing/examples etc....

**Comment by RalphSteinhagen** [comment]
Will close this since this has been contributed, merged, and released as part of the recent release.
